@extends('layouts.admin')
@section('title', 'Notifications')

@section('content')
<div class="toolbar">
    <div>
        <h1>Notifications</h1>
        <p>Email delivery attempts generated by new orders and order status changes.</p>
    </div>
</div>

<div class="table-wrap">
    <table class="table">
        <thead><tr><th>Notification</th><th>Order</th><th>Recipient</th><th>Status</th><th>Sent</th><th>Action</th></tr></thead>
        <tbody>
            @forelse($notifications as $notification)
                <tr>
                    <td><strong>{{ $notification->subject }}</strong><br><span class="muted">{{ Str::limit($notification->message, 95) }}</span></td>
                    <td>
                        @if($notification->order)
                            <a href="{{ route('admin.orders.show', $notification->order) }}"><strong>{{ $notification->order->order_number }}</strong></a>
                        @else
                            <span class="muted">No order</span>
                        @endif
                    </td>
                    <td>{{ $notification->recipient }}<br><span class="muted">{{ ucfirst($notification->channel) }}</span></td>
                    <td><span class="status-pill status-{{ $notification->status }}">{{ $statuses[$notification->status] ?? ucfirst($notification->status) }}</span></td>
                    <td>{{ $notification->sent_at?->format('M d, h:i A') ?: 'Not sent' }}</td>
                    <td>
                        <div class="table-actions">
                            @if($notification->channel === 'email')
                                <form method="POST" action="{{ route('admin.notifications.retry', $notification) }}">
                                    @csrf
                                    <button class="btn btn-primary btn-small" type="submit">Retry email</button>
                                </form>
                            @endif
                            <form method="POST" action="{{ route('admin.notifications.destroy', $notification) }}" data-confirm="Delete this notification log?">
                                @csrf @method('DELETE')
                                <button class="btn btn-danger btn-small" type="submit">Delete</button>
                            </form>
                        </div>
                    </td>
                </tr>
            @empty
                <tr><td colspan="6">No notifications yet.</td></tr>
            @endforelse
        </tbody>
    </table>
</div>
<div class="pagination">{{ $notifications->links() }}</div>
@endsection
